### ISSUE TITLE
Menu icons wrong scaling on Tablet

### ISSUE THREAD

**Issue by Nokius** [M4rtinK/modrana#118]
The menu Icon are a bit to big on the tablet.

See screenshot:
![20151010221649](https://cloud.githubusercontent.com/assets/879178/10413055/f041ec70-6f9c-11e5-9626-72ad4c7d6730.jpg)

**Comment by M4rtinK** [comment]
This should be fixed by the recent high-DPI fixes. But feel free to reopen if the issue still persists on the Jolla Tablet once the modRana version with the fix is released (0.54.x).
