### ISSUE TITLE
About page small front on Tablet

### ISSUE THREAD

**Issue by Nokius** [M4rtinK/modrana#119]
The about page on the Jolla Tablet has a bit small front also the Icon is small for the screen

See screenshot:
![20151010221713](https://cloud.githubusercontent.com/assets/879178/10413063/4da55640-6f9d-11e5-98f6-9d06d747c387.jpg)

**Comment by M4rtinK** [comment]
This should be fixed by the recent high-DPI fixes. But feel free to reopen if the issue still persists on the Jolla Tablet once the modRana version with the fix is released (0.54.x).
