### ISSUE TITLE
Map Icon small on Tablet

### ISSUE THREAD

**Issue by Nokius** [M4rtinK/modrana#120]
The icons for zoom and menu are bit small on the Tablet.

See screenshot:
![20151010222809](https://cloud.githubusercontent.com/assets/879178/10413105/6ec64568-6f9e-11e5-8422-27a85e6d43b1.jpg)

**Comment by M4rtinK** [comment]
This should be fixed by the recent high-DPI fixes. But feel free to reopen if the issue still persists on the Jolla Tablet once the modRana version with the fix is released (0.54.x).
