### ISSUE TITLE
routeing buttons have not the full label on the Tablet

### ISSUE THREAD

**Issue by Nokius** [M4rtinK/modrana#121]
The buttons:

'route here'
'clear'
'start'
'end'

have not the label fully visible. 

See screenshots:
![20151010223211](https://cloud.githubusercontent.com/assets/879178/10413119/12432558-6f9f-11e5-92cc-2af0f08e239d.jpg)
![20151010223022](https://cloud.githubusercontent.com/assets/879178/10413118/12400c74-6f9f-11e5-8df9-0b3c054f66de.jpg)

**Comment by M4rtinK** [comment]
This should be fixed by the recent high-DPI fixes. But feel free to reopen if the issue still persists on the Jolla Tablet once the modRana version with the fix is released (0.54.x).
