### ISSUE TITLE
OSM 'Hike and Bike' URL needs updating.

### ISSUE THREAD

**Issue by mikehgentry** [M4rtinK/modrana#134]
[Apologies - I hit return too early :( ]

The URL for Open Street Map 'Hike and Bike' is no longer valid.

http://wiki.openstreetmap.org/wiki/Hike_%26_Bike_Map

I tried (on Sailfish) editing /home/nemo/.config/harbour-modrana/map_config.conf to change it to 

    http://b.tiles.wmflabs.org/hikebike/

and it seems to work, although you lose the topographic information - the other server, described on the above page as 'hillshading', doesn't seem to work, but 'Hike and Bike' still seems like it might be useful, since you can overlay it on Google's 'Terrain only' for example with seemingly quite good results.

[apologies for not providing a patch, I don't really understand Github].

**Comment by M4rtinK** [comment]
Thanks for reporting the issue - it should be fixed now! :)

Also if you encounter any other map layers that don't work anymore (or some that could be added), don't hesitate to let me know. :)

And on a related note - I really need to finally write an automated test for checking if map layers still work & run it periodically. :P
