### ISSUE TITLE
Slow server leads to resubmission of jobs

### ISSUE THREAD

**Issue by rinigus** [M4rtinK/modrana#201]
As a part of the testing OSM Scout Server with Mapnik on slower hardware, I stumbled on the case where modRana was resubmitting the same tile requests while the server was processing a queue. I wonder if it would be possible to either significantly increase timeout for OSM Scout Server or just abolish it. If the server is not running the connection would not be established and it should be all fine on modRana side.

**Comment by M4rtinK** [comment]
I'll have to check in more detail (I haven't read that part of modRana source code in a while) but I guess modRana might just be submitting a tile download request again, eq. due to user re-visiting an an area that triggered the previously started download request - I'm not sure at the moment if there is a check if a tile is not already being downloaded before a download request is added to the tile download pool.

Or are you seeing some connection timeout messages in the modRana logs, etc. ?

**Comment by rinigus** [comment]
I'll have to look into the logs. It seemed that the resubmission was triggered by timeouts within modRana code, but I have to look into it more carefully. And produce the logs.

**Comment by rinigus** [comment]
Just submitted PR with the tile download timeout dropped (set to None). This fixed problems on Nexus 4 and probably on some other slower phones when using complex map tile generation styles with OSM Scout Server.

In terms of rendering efficiency, would be great to get support for large tiles (1024x1024). That would allow to render with a smaller waste than using 256x256 leads to. But that is a separate issue.

**Comment by M4rtinK** [comment]
> Just submitted PR with the tile download timeout dropped (set to None). This fixed problems on Nexus 4 and probably on some other slower phones when using complex map tile generation styles with OSM Scout Server.

Should be fixed by https://github.com/M4rtinK/modrana/pull/204.

> 
> In terms of rendering efficiency, would be great to get support for large tiles (1024x1024). That would allow to render with a smaller waste than using 256x256 leads to. But that is a separate issue.

I know & I do certainly have it on my roadmap - it's slightly complicated by the comprehensive overlay support modRana has, so it ideally needs to be able to work with tiles of different sizes at the same time and scale them accordingly.

But support for OSM Scout routing  V2 & local POI database UI come first as I'll need those for my summer travels in Japan shortly. :)

**Comment by rinigus** [comment]
I am closing the issue since its resolved now.

I wonder how good is your Japanese? There is currently a tiny-tiny issue - OSM is all in native language. We don't import English version, so you cannot search in English, see maps in English, ... If you are not up to it in Japanese then either I have to fix it before that or you better start learning it. But closing this issue with the comment

**Comment by M4rtinK** [comment]
> I wonder how good is your Japanese? 
That's a good question - I would say I can understand spoken Japanese and generally understand the meaning but I'm still mostly working on my Kanji reading skills to get them to an usable level. But hopefully another member of our 3 member group should be quite a bit better, including better Kanji skills.

>There is currently a tiny-tiny issue - OSM is all in native language. We don't import English version, so you cannot search in English, see maps in English,
Oh, I've looked at the data for Tokyo and I think I understand it now. For example here on this random streat:

http://www.openstreetmap.org/way/44776176

there is the `name` key: 清洲橋通り
and the `name:en` key: Kiyosubashi-dori

And indeed searching for "Kiyosubashi-dori" using location search does not return anything from the OSM Scout Geocoder while Nominatim seems to find it.

So if I understand it correctly - only `<key>` elements are included in the data at the moment, not `<key>:<language code>`, right ?

> ... If you are not up to it in Japanese then either I have to fix it before that or you better start learning it. 

While I do think it would be pretty useful (not just for me but others who understand English & the latin alphabet but travel to a non-latin alphabet country) I really don't want to put you under any pressure - you are already doing A LOT of work on this wonderful project (thanks a lot yet again! :) ) and I don't want to needlessly disrupt your plans.

And I should still be able to use the native maps for general navigation (this is street, this is river, this is a tram line, train station, etc.) & type based amenity search should IMHO also work regardless (find nearest ATM/convenience store/restaurant/etc.). I'll probably also have some limited connectivity available, so I might be also able to use some online search if needed (Nominatim, Google (bleh), etc.). Point-to-point routing should also work fine.

BTW, is there actually a Japanese input method for Sailfish OS ? I think I've seen just some RFEs on Together and that was it. :)

I'll be setting out for Japan on the 13th of July and will be there for 3 weeks. I'll have my Jolla C & Jolla Tablet with me so I'm looking forward to some modRana & OSM Scout Server field testing. :) Theoretically I might be even able of doing some minor modRana improvements/changes/fixing (I'll have a [foldable bluetooth keyboard](https://www.amazon.com/iClever-Backlight-Aluminum-Bluetooth-Smartphone/dp/B018K5EJCQ) with) but only time will tell how realistic idea it is. :)

>But closing this issue with the comment
Sure. :)

**Comment by rinigus** [comment]
I opened related issue, let's see what I can do

**Comment by rinigus** [comment]
Sorry for not replying properly, I'm traveling at present. Don't know much Japanese input . but the Latin names would be useful and I have been thinking about it as well . not sure I'll be in time , but let's see

**Comment by rinigus** [comment]
English-enabled Japan map will not be ready in time, unfortunately. The geocoder works already, but I would need to adjust few styles for Mapnik and reimport the planet to make it work. That may take some time, unfortunately.

Enjoy the trip!

**Comment by M4rtinK** [comment]
> English-enabled Japan map will not be ready in time, unfortunately. The geocoder works already, but I would need to adjust few styles for Mapnik and reimport the planet to make it work. That may take some time, unfortunately.

That's totally fine and there is definitely no need to rush things. Looks like I might be able to get a data SIM, so should be able to use online services in case I can't figure out the given part of the map as long as I'm in an area with coverage. And if I'm out of coverage the map as it is now should be able to get me back to civilization just fine. :)

> 
> Enjoy the trip!

Thanks a lot! :)
