### ISSUE TITLE
Feature-request: Multilingual

### ISSUE THREAD

**Issue by Caballlero** [M4rtinK/modrana#209]
Hello M4rtink 

Any plans to start  translate modrana into several languages?

**Comment by M4rtinK** [comment]
I have preliminary plans for that - I'm marking strings as translatable in the Qt 5 GUI, etc. But as some strings come from the substantial Python backend it will be more difficult to make translatable (eq. need to extract & make translatable string from both Python & QML) than a classic mostly QML application with a light C++ backend.

**Comment by Caballlero** [comment]
Thank you very much M4rtink. I am ready to translate :  )
